/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ProgressDialog: typeof import('./src/components/ProgressDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
