/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundTaskOverlay: typeof import('./src/components/BackgroundTaskOverlay.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    HelpPanel: typeof import('./src/components/HelpPanel.vue')['default']
    LatencyBar: typeof import('./src/components/LatencyBar.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    ProgressDialog: typeof import('./src/components/ProgressDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ToolchainSelector: typeof import('./src/components/ToolchainSelector.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
