name: Test

on:
  workflow_dispatch:

concurrency:
  group: test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: pnpm/action-setup@v6.0.8
        with:
          version: 10
          run_install: true

      - name: Use Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 26
          cache: "pnpm"

      - name: Run unit tests
        run: pnpm test
